steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/alpine', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'echo', 'Akila@19', '|', 'docker', 'login', '-u', 'jjino', '--password-stdin' ]
images:
- 'gcr.io/$PROJECT_ID/alpine'
