steps:
  # Configure a kubectl workspace for this project
  - name: gcr.io/cloud-builders/kubectl
    args:
      - get nodes
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-east1
  _CUSTOM_CLUSTER:  standard-cluster-1
