steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud components install kubectl
    gcloud container clusters get-credentials  --project="kube-259906" standard-cluster-1 --region us-east-1
    kubectl get nodes